name: test

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master , dev ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      # - name: set up JDK 1.11
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.11
      - name: Install flutter
        run: |
          sudo snap install flutter --classic
          flutter doctor
      - name: Run flutter pub get
        run: |
          cd src
          flutter pub get
      - name: Unit tests
        run: |
          cd src
          flutter test test/test.dart
